import type { Metadata } from "next";
import "./globals.css";
// import "./assets/css/embla.css";
import { Inter } from "next/font/google";

const inter = Inter({
  weight: ["900"], // Inter Black corresponds to 900 weight
  subsets: ["latin"],
  variable: "--font-inter-black",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-[#1B2316] antialiased`}>
        {children}
      </body>
    </html>
  );
}
